(package "vlc-player"
         "0.0.8"
         "Play video using VLC")

(website-url "https://github.com/jcs090218/vlc-player")
(keywords "multimedia" "video" "vlc" "buffering" "images")

(package-file "vlc-player.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "24.3")
(depends-on "s")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
